version: '3.8'
services:
  marmo:
    image: marmo:test
    stdin_open: true   # -i
    tty: true          # -t
    volumes:
      - /media/3a7895b8-6fc9-4b13-b3ed-2045ee637322/viddata:/app/vid
      - .:/app/marmo3Dpose
    command: bash